src/app/(route)/timetable/page.tsx
src/app/dummyData/timetable/getTimetable.json
src/app/dummyData/timetable/getTimetableRecommand.json

`feat/timetable` → `dev`
<br/>
- 와이어프레임을 기반으로 시간표 페이지 레이아웃을 구현했습니다.
- 시간표의 빈 부분을 누르면, 오른쪽에 패널이 나타나며 즐겨찾기 목록과 공석 추천 목록이 나타납니다.
- 즐겨찾기 목록과 공석 추천 목록의 아이템이 많아지면 전체 스크롤이 아닌, 목록 내에서 스크롤되게 구현했습니다.
- 창의 너비가 줄어들 때, 양 옆의 여백이 일정하게 줄어들도록 하였고, 모바일 반응형은 아직 정확한 기준이 나오지 않아 구현하지 않았습니다.
<br/>
<br/>
- 강의 목록
<br/>
- [`feat/timetable` #11 ]

feat(timetable): 시간표 레이아웃 구현

---

next.config.ts
src/app/(route)/(main)/page.tsx
src/app/(route)/lecture-list/page.tsx
src/app/_components/Card/Card.tsx
src/app/_error.tsx
src/app/dummyData/lecture-list/getLectureList.json

`feat/card-component` → `dev`
<br/>
- 강의 목록, 메인 페이지, 강사 프로필 페이지에 공통으로 사용되는 카드 컴포넌트 구현
- 세 페이지 모두 공통으로 들어가는 요소인 이미지, 제목, 카테고리는 컴포넌트로 구현
- 시간과 즐겨찾기 버튼의 유무는 선택적으로 전달할 수 있도록 옵션으로 구현
- 강연자와 신청 버튼은 children으로 전달하여 유연하게 추가할 수 있도록 구현
<br/>
| 강의 목록 | 메인 | 강사 프로필|
|---|---|---|
| ![스크린샷 2025-03-10 오후 8 26 22](https://github.com/user-attachments/assets/31878d17-53d7-4499-a3c0-9c8cdc63015e) | ![스크린샷 2025-03-10 오후 8 28 37](https://github.com/user-attachments/assets/b3bd868c-b195-4a18-942e-27a3fba88b92) | ![스크린샷 2025-03-10 오후 8 28 55](https://github.com/user-attachments/assets/f9d5da2d-b70a-4e43-ad62-d7f3b1b62c43) |
<br/>
- 강의 목록 구현
<br/>
- [`feat/card-component` #14

feat(card component): 카드 컴포넌트 구현

---

src/app/(route)/lecture-list/page.tsx
src/app/_components/Card/Card.tsx
src/app/_components/DayTab/DayTab.tsx
src/app/_components/DayTab/groupBy.ts
src/app/_error.tsx
src/app/dummyData/lecture-list/getLectureList.json
src/app/error.tsx
src/app/layout.tsx

`feat/lecture-list` → `dev`
<br/>
- 와이어프레임을 기반으로 강의 목록 레이아웃 구현
- 강의 목록과 시간표 페이지에 공통으로 사용되는 DayTab 컴포넌트 구현
- 날짜별 강의 목록 필터링 구현
- 카테고리별 강의 목록 필터링 구현
- 시간대별 강의 목록 필터링 구현
- 다크 모드 적용
<br/>
| 날짜별, 시간대별  | 카테고리별  |
|---|---|
| <img width="754" alt="스크린샷 2025-03-11 오후 6 12 56" src="https://github.com/user-attachments/assets/790d479a-3746-40d7-879c-74fc29cb17a1" /> |  <img width="754" alt="스크린샷 2025-03-11 오후 6 13 15" src="https://github.com/user-attachments/assets/09302e87-d7da-4a82-a0b4-434d8ddd0299" /> |
<br/>
- 시간표 레이아웃 변경
<br/>
- [`feat/lecture-list`] #21

feat(lecture-list): 강의 목록 구현

---

src/app/(route)/timetable/page.tsx
src/app/_components/DayTab/DayTab.tsx

`feat/timetable` → `dev`
<br/>
- 변경된 시간표 와이어프레임 반영
- 기존에 Day1, Day2, Day3이 각 열에 있는 표 형태에서, 각 날짜를 선택하면 해당 날짜의 시간표만 조회하는 형태로 변경
- DayTab 컴포넌트 활용
<br/>
|---|---|
| <img width="750" alt="스크린샷 2025-03-12 오후 7 34 32" src="https://github.com/user-attachments/assets/df70c017-940b-4ce9-8942-46e4e9b8aa83" /> | <img width="752" alt="스크린샷 2025-03-12 오후 7 34 15" src="https://github.com/user-attachments/assets/9769b838-d3d5-43bc-94aa-f4ee1a63415a" /> |
<br/>
- 즐겨찾기 목록 추가
<br/>
- [`feat/lecture-list`] #26

design(timetable): 시간표 레이아웃 변경

---

src/app/(route)/layout.tsx
src/app/layout.tsx

`fix/darkmode` → `dev`
`feat/main/header` → `feat/main`
<br/>
- layout 중복으로 하이드레이션 오류가 있었음.
- `src/app/layout/tsx` 제거해서 해결
<br/>
<br/>
- [`fix/darkmode`#32]

Fix(darkmode):  하이드레이션 오류 수정

---

src/app/_styles/globals.css

`fix/font-contentEdit` → `dev`
<br/>
- 글꼴 적용 안되던 오류 해결
<br/>
<br/>
- 헤더 스타일 수정
<br/>
- [`fix/font-contentEdit` #38]

fix(font-contentEdit): 폰트 굵기 적용되지 않던 문제 해결

---

src/app/(route)/timetable/page.tsx
src/app/_components/DayTab/DayTab.tsx
src/app/dummyData/timetable/getWishlist.json

`feat/wishlist` → `dev`
<br/>
- 시간표 페이지에 즐겨찾기 목록 버튼 추가
- 사용자가 즐겨찾기한 모든 강의 목록을 보여줌
- 오른쪽에 목록이 나타날 때, 헤더부분은 상단 고정되도록 레이아웃 수정
<br/>
<br/>
- 즐겨찾기 기능 구현
<br/>
- [`feat/lwishlist`] resolve #33

feat(wishlist): 즐겨찾기 목록 추가

---

src/app/(route)/(main)/mainComponent/SecSection.tsx
src/app/(route)/(main)/page.tsx
src/app/(route)/instructor/[id]/page.tsx
src/app/(route)/lecture-list/page.tsx
src/app/_components/Card/Card.tsx

`design/card` → `dev`
<br/>
- Hi-Fi Wireframe을 기반으로 카드 컴포넌트의 디자인 수정
- 카드 컴포넌트가 사용되는 모든 페이지에서 즐겨찾기 버튼이 항상 렌더링되도록 변경 (조건부 렌더링 제거)
- 메인 페이지와 강의 목록 페이지에서 동일한 요소를 렌더링하도록 디자인을 통일하면서 컴포넌트 구조 변경
- spacing(margin, padding, gap) 적용
- style(align, color, radius) 적용
- font(size, weight, line-height) 적용
<br/>
|---|---|
| ![image](https://github.com/user-attachments/assets/0085e90a-e9f6-46a1-a9e6-e771fc1c1375) | <img width="290" alt="스크린샷 2025-03-14 오전 10 53 33" src="https://github.com/user-attachments/assets/5e218e13-1c32-4d7b-b8fd-2df64f76fdb6" /> |
<br/>
- 즐겨찾기 기능 구현
<br/>
- [`design/card`] #43

design(card component): 카드 컴포넌트 구조 및 디자인 변경

---

eslint.config.mjs
package-lock.json
package.json

`chore/eslint` → `dev`
<br/>
- 버튼 라벨링 없을시 warn
- 클릭 이벤트가 있는 요소에 키보드 이벤트가 없을 시 warn
- span, div 요소에서 이벤트 사용시 warn
- 비대화 요소(span, div, li, ol 등등)에서 이벤트 사용시 warn
<br/>
<br/>
- 알림 퍼블리싱
- 마이 페이지 퍼블리싱
<br/>
- [chore/eslint #44 ]

Chore(eslint): 웹 접근성 규칙 추가

---

eslint.config.mjs
src/app/(route)/layout.tsx
src/app/(route)/mypage/[id]/page.tsx
src/app/_styles/globals.css
tailwind.config.ts

`design/my-page` → `dev`
<br/>
- 마이 페이지 초기 구조 퍼블리싱
-  버튼들의 색상이 모두 동일하여 **재사용 가능한 `.btn` 클래스 추가**
- `.btn` 클래스는 배경색, 글자색만 반영
- 버튼마다 `padding` 및 `border-radius` 값이 달라 따로 이 부분은 적용하지 않음
- **다크 모드 자동 반영** 
**예시**
```typescript
return <div class="btn px-2 py-4"/>;
```
<br/>
마이페이지
<br/>
- 메인 페이지 퍼블리싱 
- 알림 기능 개발
<br/>
- [`design/my-page` #49]

design(my-page): 마이페이지 퍼블리싱

---

src/app/_components/Card/Card.tsx

`design/card` → `dev`
<br/>
- 카드 컴포넌트에 배경색 추가하여 뒤 배경이 비쳐 보이는 문제 해결
<br/>
|---|---|
| ![image](https://github.com/user-attachments/assets/0e634b4c-a955-420f-b122-2a4328896693) | <img width="301" alt="스크린샷 2025-03-17 오전 9 27 37" src="https://github.com/user-attachments/assets/e64cf786-3d43-4adf-bb86-08cab82b8fb3" /> |
<br/>
- 강의 목록 디자인 수정
<br/>
- [`design/card`] #60

design(card): 카드 컴포넌트 배경색 추가

---

src/app/_components/Header/Alarm/Alarm.tsx
src/app/_components/Header/Header.tsx
src/app/_components/Header/HeaderNav/HeaderNav.tsx
src/app/_components/Nav/navigation/HeaderNav.web.tsx

`fix/resize` → `dev`
<br/>
- 기존에 알림에서 설정된 타임아웃이 제대로 정리되지 않아, 모바일 → 웹 → 모바일 전환 시 더미 데이터 호출 함수가 반복 실행됨.
- 이로 인해 리소스가 누적되어 오류가 발생하는 문제가 확인됨.
- 더미 데이터 호출 함수를 알림에서 헤더로 이동하여 해당 문제를 해결함.
- 헤더 사이즈 모바일 80px로 수정
<br/>
<br/>
- 텍스트 에디터 개발
<br/>
- [`fix/resize` #63]

fix(resize): 리사이즈 에러 픽스

---

src/app/(route)/layout.tsx
src/app/(route)/lecture-list/page.tsx
src/app/_components/Card/Card.tsx
src/app/_components/DayTab/DayTab.tsx
src/app/dummyData/lecture-list/getLectureList.json

`design/lecture-list` → `dev`
<br/>
- 기존 low-fi wireframe을 기반으로 구현했던 강의 목록 UI를 hi-fi wireframe을 반영하여 수정
- 전체 페이지 레이아웃의 컨텐츠 최대 너비 설정 및 가운데 정렬
- DayTab 컴포넌트 디자인 수정
- 다크모드일때 카드 배경색 추가
- 강의 목록의 세션개수를 전체 세션 개수에서 **선택한 날짜의 총 세션 개수**로 변경
<br/>
|---|---|
| ![스크린샷 2025-03-18 오전 9 06 57](https://github.com/user-attachments/assets/b20d18c3-5486-4fb6-a8b9-ca2b8d197a9d) | ![스크린샷 2025-03-18 오전 9 06 33](https://github.com/user-attachments/assets/836c59d8-0ae0-4606-a56a-93584e59dbdd) |
<br/>
- 시간표 디자인
<br/>
- [`design/lecture-list`] #62

design(lecture list): 강의 목록 디자인 수정

---

src/app/(route)/lecture/[id]/page.tsx
src/app/(route)/timetable/page.tsx
src/app/dummyData/timetable/getTimeWish.json

`design/timetable` → `dev`
<br/>
- 기존 **low-fi wireframe**을 기반으로 구현했던 시간표 페이지 UI를 hi-fi wireframe을 반영하여 수정  
- 선택한 시간의 즐겨찾기 목록에 `lectureId` 필드 추가
- `lectureId`를 기반으로 즐겨찾기 토글 
<br/>
|시간표| 빈 시간 선택|
|---|---|
|![스크린샷 2025-03-19 오후 1 15 51](https://github.com/user-attachments/assets/850ab117-5ca3-450b-b040-df074364cff2) | ![스크린샷 2025-03-19 오후 1 15 39](https://github.com/user-attachments/assets/f0da0986-0d0e-4d64-9ed6-c2db51b3269d) |
<br/>
- 컴포넌트 분리
<br/>
- [`design/timetable`] #77

design(timetable): 시간표 디자인 수정

---

src/app/(route)/timetable/page.tsx
src/app/(route)/timetable/timetableComponent/ListCard.tsx
src/app/_components/Wish/WishButton.tsx
src/app/_types/Timetable/Lecture.type.ts

`feat/list-card` → `dev`
<br/>
- 시간표 페이지에서 전체 즐겨찾기 목록, 빈 시간 클릭 시 나오는 즐겨찾기 목록, 추천 강의 목록에서 동일한 UI로 반복되는 강의 목록 카드를 ListCard 컴포넌트로 분리
- 시간표 페이지에 관련된 타입 분리
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [`feat/list-card`] #79

feat(ListCard): ListCard 컴포넌트 분리

---

src/app/(route)/layout.tsx
src/app/_components/LayoutWrapper.tsx

`fix/main-width` → `dev`
<br/>
- 메인 페이지의 배경색이 전체 너비를 채우지 않는 문제를 해결하기 위해 `LayoutWrapper.tsx`를 추가하여 레이아웃을 분리
- `usePathname()`을 활용해 메인 페이지 여부 확인 후, 레이아웃 동적 변경
- 메인 페이지에서는 `w-full` 적용
- 다른 페이지에서는 기존 `max-w-7xl mx-auto` 레이아웃 유지
<br/>
|---|---|
| ![image](https://github.com/user-attachments/assets/17301c5a-6b68-44c5-82a9-d9d173ffbf63) | ![스크린샷 2025-03-20 오후 5 00 32](https://github.com/user-attachments/assets/505c0018-2de9-4171-878c-a44942f6c47b) |
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [`fix/main-width`] #82

fix(main): 메인페이지 배경색 너비 문제 해결

---

next.config.ts
src/app/(route)/(main)/mainComponent/SecSection.tsx
src/app/(route)/(main)/mainComponent/component/OptionList.tsx
src/app/(route)/(main)/mainComponent/component/SectionList.tsx
src/app/_types/Lectures/lectures.type.ts
src/app/_utils/Main/getLectures.ts

`design/mainPage` → `dev`
<br/>
- 메인 페이지 섹션2 일부 마진 수정
- 섹션2 강의 리스트 데이터 API 연동
<br/>
<br/>
- 강의 생성 API 연결
- 알림 API 연결
<br/>
- [design/mainPage #67]

design(mainPage): api 연동 및 이미지 경로 추가

---

package-lock.json
package.json
src/app/(route)/write/page.tsx
src/app/(route)/write/util/upload.ts
src/app/_components/Header/Alarm/Alarm.tsx
src/app/_components/Header/Alarm/AlarmList.tsx
src/app/_components/Header/HeaderNav/HeaderNav.tsx
src/app/_hooks/nav/useAlarm.ts
src/app/_store/Header/useAlarmStore.ts
src/app/_types/Header/Alarm.type.ts
src/app/_types/Write/write.type.ts
src/app/_utils/api/response.ts
src/app/api/auth/admin/route.ts
src/app/api/auth/user/refresh/route.ts
src/app/api/auth/user/route.ts

`feat/api/write-alarm` → `dev`
<br/>
- add `lz-string // 강의 컨텐츠 데이터 압축`
- add `event-source-polyfill // 이벤트 스트림에 헤더 포함 가능한 라이브러리`
- 현재 `/wrtie` 경로에 들어가면 로그인 유무 상관없이 강의 생성 가능함.
- 유의) `title`과 `email`은 반드시 독립적이여야 함.
- 현재 이벤트 스트림을 내려주는 엔드포인트가 없음
- 알림 창을 열었을 때 폴링처럼 모든 알림 데이터를 가져오게 임시 구현함
<br/>
`/write`
알림
<br/>
- 잘못된 강의 데이터 삭제 및 더미데이터 생성
- 메인 페이지 및 알림 컴포넌트 퍼블리싱
<br/>
- [`feat/api/write-alarm`  #87]

Feat[write-alarm]: 강의 생성 / 알림 기능 api 연동

---

src/app/(route)/lecture-list/page.tsx
src/app/_components/Card/Card.tsx
src/app/_components/DayTab/groupBy.ts
src/app/_store/LectureList/useLectureStore.ts

`feat/lecture-list-api` → `dev`
<br/>
- 강의 목록 API를 호출하여 데이터를 불러오도록 연동
- 강의 목록에서 시간대별 그룹화 및 렌더링 시 `NaN`이 표시되는 문제 해결
- 강의 데이터가 특정 날짜에 없는 경우에도 Day1,2,3 탭 유지하도록 날짜별 그룹화 로직 수정
- 카드 컴포넌트의 제목 영역이 차지하는 높이 고정
<br/>
|---|---|
| <img width="1512" alt="스크린샷 2025-03-21 오전 9 23 43" src="https://github.com/user-attachments/assets/f214098b-3444-4261-bdb0-256b96ce8702" /> | ![스크린샷](https://github.com/user-attachments/assets/f45a9ec1-bd2f-492b-b8b8-9b169b09ef2e) |
| 제목 높이 고정 전 | 제목 높이 고정 후 | 제목이 3줄이 넘어가도 두줄까지만 보인다 |
|---|---|---|
| <img width="614" alt="스크린샷 2025-03-21 오후 1 55 28" src="https://github.com/user-attachments/assets/079eb727-ad73-43be-89da-4a077a4f661e" /> | ![스크린샷 2025-03-21 오후 2 09 35](https://github.com/user-attachments/assets/436e2647-039c-479d- …

feat(lecture list): 강의 목록 API 연결

---

src/app/(route)/admin/page.tsx

`feat/admin/dashboard` → `dev`
<br/>
- 더미 데이터 부분 삭제 후 API 연결
- 디자인에 맞춰서 색상 변경
<br/>
<br/>
- 알림 페이지 API 연결해서 강의 목록 불러오기
- 알림 페이지 알림 전송 기능 구현
<br/>
- [feat/admin/dashboard #100 ](이슈 주소)

feat/design(admindashboard): 어드민 대시보드 API 연동, UI 수정

---

src/app/(route)/lecture/[id]/page.tsx
src/app/(route)/lecture/component/QuestionSection.tsx

`fix/login-check`→ `dev`
<br/>
- 사전 질문 등록 시 로그인 여부 확인
- 강의 상세 페이지의 즐겨찾기 버튼 클릭 시 로그인 여부 확인
<br/>
<br/>
- 시간표 반영 문제 고치기
<br/>
- [`fix/login-check`] #128

fix(lecture): 강의 상세페이지 로그인 여부 확인

---

src/app/(route)/admin/alarm/page.tsx

`feat/admin/alarm` → `dev`
<br/>
- API 연동하여 강의 목록 불러옴
- 알림 전송 기능 구현
- 디자인에 맞게 UI 수정
<br/>
<br/>
- 다크모드 구현
- 대시보드 API 연결 수정
<br/>
- [feat/admin/alarm #96 ](이슈 주소)

feat/design(adminAlarmPage): API 연동, UI 수정

---

src/app/(route)/lecture/[id]/page.tsx
src/app/(route)/lecture/component/QuestionSection.tsx

`design/lecture-detail` → `dev`
<br/>
- 강의 상세페이지 반응형 적용
- 로그인 안한 상태에서 강의 자료 다운로드 disable
<br/>
<br/>
- 강의 목록 반응형
- 시간표 반응형
<br/>
- [`design/lecture-detail`] #137

design(lecture detail): 강의 상세페이지 반응형

---

src/app/_hooks/nav/useAlarm.ts

`fix/alarm` → `dev`
<br/>
- 액세스 토큰의 유효성이 다 끝났음에도 불구하고, 계속 알림을 신청하는 에러가 있었음.
- 알림을 실패 했을 때 액세스 토큰을 삭제하게 구현하여 이를 개선함
<br/>
<br/>
<br/>
- [fix/alarm #129]

fix(alarm): 액세스 토큰 권한이 없을 때 알림 요청하는 오류 픽스

---

next.config.ts
src/app/(route)/lecture-list/component/list.tsx
src/app/(route)/lecture/[id]/page.tsx
src/app/(route)/lecture/component/QuestionSection.tsx
src/app/(route)/timetable/page.tsx
src/app/(route)/timetable/timetableComponent/ListCard.tsx
src/app/_components/TextViewer/TextViewer.tsx
src/app/assets/Timetable/Vector 3.svg

`design/qa/lecture` → `dev`
<br/>
- 카카오 프로필 이미지 표시 오류 수정
- 시간표 페이지 디자인 QA 반영
- 텍스트 색
- 여백
- 아이콘 색
- 버튼 크기
- 강의 상세 페이지 디자인 QA 반영
- 텍스트 색
- 인풋 필드 포커싱
- 버튼 크기
- 질문 여러줄일때 정렬
- 본인 질문만 수정/삭제 버튼 표시
- 강의 목록 페이지 디자인 QA 반영
- 텍스트 색
- rounded
- 여백
- 아이콘 크기
- 목록에 카드 너비 조절해서 여백 없애는 것 -> 기존 방식 그대로 하기로 함
<br/>
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [`design/qa/lecture`] #156

design(lecture,list,timetable): 디자인 QA 반영

---

src/app/(route)/lecture-list/component/list.tsx

`fix/filtering` → `dev`
<br/>
- 카테고리 필터링 후에 강의가 없는 시간 라벨 제거
- 강의 개수도 해당 날짜의 전체 강의 개수가 아닌, 필터링 후 강의 개수로 변경
<br/>
| 변경 전 | 변경 후|
|---|---|
| ![스크린샷 2025-03-31 오후 5 30 03](https://github.com/user-attachments/assets/f2af5965-e056-4c87-9983-d9fc6c0afeda) | ![스크린샷 2025-03-31 오후 5 48 43](https://github.com/user-attachments/assets/daf71ae7-31de-4d15-b84f-5af4db27aca5) |
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [`fix/filtering`] #168

fix(filtering): 카테고리 필터링 후 빈 시간 라벨 제거

---

src/app/(route)/lecture-list/component/list.tsx
src/app/(route)/lecture/component/QuestionSection.tsx

`design/qa/etc` → `dev`
<br/>
- 디자인 QA 중 빠트린 내용 수정
<br/>
| 강의 목록 다크모드 전 | 후 |
|---|---|
| ![스크린샷 2025-04-01 오전 9 06 50](https://github.com/user-attachments/assets/c4f315f4-0d6c-4f22-aeb3-b891a3a08892) | ![스크린샷 2025-04-01 오전 9 06 42](https://github.com/user-attachments/assets/c434b8a9-06a0-4698-ac10-cfb892f36cad) |
| 강의 상세 반응형 전 | 후 |
|---|---|
| ![스크린샷 2025-04-01 오전 9 05 59](https://github.com/user-attachments/assets/9a613208-3f06-4e4b-b52e-b68700f66d87) | ![스크린샷 2025-04-01 오전 9 06 11](https://github.com/user-attachments/assets/f4703ef4-b134-41d2-8648-2af36a41458d) |
<br/>
- 내일 할 일을
- 적어주세요
<br/>
- [`design/qa/etc`] #173

design(lecture list, detail): 다크모드, 반응형 수정
